name: Create and Delete Issue Branch

on:
  issues:
    types: [ assigned ]
  issue_comment:
    types: [ created ]
  pull_request:
    types: [ closed ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

  delete_merged_branch:
        if: >
          github.event.pull_request.merged == true &&
          github.event.pull_request.head.ref != 'main'
        runs-on: ubuntu-latest
        steps:
          - name: Delete Merged Branch
            uses: dawidd6/action-delete-branch@v3.1.0
            with:
              github_token: ${{ secrets.PAT_TOKEN }}
              branches: ${{ github.event.pull_request.head.ref }}
